spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/tiny_url?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 30000
#      connection-timeout: 20000
#      max-lifetime: 1800000
tinyurl:
  prefix: https://rryan.me/s/
  expireSeconds: 604800